M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu25.04.1} date 2025-12-27T12:18:58+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-27T12:18:58+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu25.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X145.11Y-46.855
X150.89Y-46.855
M30
